In [5]:
import numpy as np 

In [16]:
grade=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
grade

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
grade[0:2,2]

array([3, 6])

In [18]:
grade[2,:]


array([7, 8, 9])

In [19]:
grade[1:,1:]

array([[5, 6],
       [8, 9]])

In [7]:
np.array([(1,2,3),(4,5,6),(7,8,9)])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr[2,2]

TypeError: array indices must be integers

In [20]:
### load the dataset